import './style.css'
export {default as Favorites} from './favorites' 
export {default as FilmsByGenre} from './films-by-genre' 
export {default as PopularFilms} from './popularFilms'
export {default as SearchResults} from './searchResults'
export {default as SinglePage} from './single-page'